IF OBJECT_ID('dbo.MOTO', 'U') IS NOT NULL DROP TABLE dbo.MOTO;
IF OBJECT_ID('dbo.USUARIO', 'U') IS NOT NULL DROP TABLE dbo.USUARIO;
IF OBJECT_ID('dbo.PATIO', 'U') IS NOT NULL DROP TABLE dbo.PATIO;

CREATE TABLE USUARIO (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  USERNAME NVARCHAR(100) NOT NULL UNIQUE,
  PASSWORD NVARCHAR(100) NOT NULL,
  PERFIL NVARCHAR(50) NOT NULL
);

CREATE TABLE PATIO (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NOME NVARCHAR(100) NOT NULL,
  ENDERECO NVARCHAR(255) NOT NULL
);

CREATE TABLE MOTO (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  PLACA NVARCHAR(20) NOT NULL UNIQUE,
  MODELO NVARCHAR(100) NOT NULL,
  PATIO_ID INT NOT NULL,
  FOREIGN KEY (PATIO_ID) REFERENCES PATIO(ID)
);

-- Inserts
INSERT INTO USUARIO (USERNAME, PASSWORD, PERFIL) VALUES ('admin', '{noop}admin123', 'ROLE_ADMIN');
INSERT INTO USUARIO (USERNAME, PASSWORD, PERFIL) VALUES ('user', '{noop}user123', 'ROLE_FUNCIONARIO');

INSERT INTO PATIO (NOME, ENDERECO) VALUES ('Patio Norte', 'Rua XPTO, 123');
INSERT INTO PATIO (NOME, ENDERECO) VALUES ('Patio Sul', 'Avenida ABC, 456');

INSERT INTO MOTO (PLACA, MODELO, PATIO_ID) VALUES ('ABC1D23', 'Mottu Sport 110i', 1);
INSERT INTO MOTO (PLACA, MODELO, PATIO_ID) VALUES ('DEF4G56', 'Mottu Delivery 2023', 2);
