spring.datasource.url=jdbc:sqlserver://mottu-sql.database.windows.net:1433;database=mottu-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=adminuser
spring.datasource.password=SenhaForte@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false
spring.flyway.validate-on-migrate=false