-- =============================================================================
-- Sprint 3 - Database
-- Integrantes: Gabriel Camargo (RM557879), Kauan Felipe (RM557954), Vinicius Alves (RM551939)
-- =============================================================================

-- CRIAÇÃO DAS TABELAS
-- =============================================================================

-- Tabela Filial
CREATE TABLE filial (
    id_filial NUMBER(9) PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    endereco VARCHAR2(200) NOT NULL
);

-- Tabela StatusMoto
CREATE TABLE statusmoto (
    id_status NUMBER(9) PRIMARY KEY,
    descricao VARCHAR2(50) NOT NULL
);

-- Tabela Patio
CREATE TABLE patio (
    id_patio NUMBER(9),
    filial_id_filial NUMBER(9),
    nome VARCHAR2(100) NOT NULL,
    localizacao VARCHAR2(200) NOT NULL,
    largura NUMBER(10,2) NOT NULL,
    comprimento NUMBER(10,2) NOT NULL,
    area_total NUMBER(10,2) NOT NULL,
    PRIMARY KEY (id_patio, filial_id_filial),
    FOREIGN KEY (filial_id_filial) REFERENCES filial(id_filial)
);

-- Tabela Camera
CREATE TABLE camera (
    id_camera NUMBER(9),
    patio_id_patio NUMBER(9),
    patio_id_filial NUMBER(9),
    localizacao VARCHAR2(200) NOT NULL,
    modelo VARCHAR2(100) NOT NULL,
    PRIMARY KEY (id_camera, patio_id_patio, patio_id_filial),
    FOREIGN KEY (patio_id_patio, patio_id_filial) REFERENCES patio(id_patio, filial_id_filial)
);

-- Tabela Leitura
CREATE TABLE leitura (
    id_leitura NUMBER(9) PRIMARY KEY,
    data_hora TIMESTAMP(0) NOT NULL
);

-- Tabela Moto
CREATE TABLE moto (
    id_moto NUMBER(9) PRIMARY KEY,
    placa VARCHAR2(10) UNIQUE NOT NULL,
    ano_fabricacao DATE NOT NULL,
    sensor_iot_id_sensor NUMBER(9),
    statusmoto_id_status NUMBER(9),
    patio_id_patio NUMBER(9),
    patio_filial_id_filial NUMBER(9),
    FOREIGN KEY (statusmoto_id_status) REFERENCES statusmoto(id_status),
    FOREIGN KEY (patio_id_patio, patio_filial_id_filial) REFERENCES patio(id_patio, filial_id_filial)
);

-- Tabela Sensor_IoT
CREATE TABLE sensor_iot (
    id_sensor NUMBER(9) PRIMARY KEY,
    tipo VARCHAR2(50) NOT NULL,
    fabricante VARCHAR2(100) NOT NULL,
    moto_id_moto NUMBER(9),
    FOREIGN KEY (moto_id_moto) REFERENCES moto(id_moto)
);

-- Atualizar foreign key da tabela moto para sensor_iot
ALTER TABLE moto ADD FOREIGN KEY (sensor_iot_id_sensor) REFERENCES sensor_iot(id_sensor);

-- Tabela de relacionamento Sensor_Leitura
CREATE TABLE sensor_leitura (
    sensor_iot_id_sensor NUMBER(9),
    leitura_id_leitura NUMBER(9),
    valor NUMBER(10,2) NOT NULL, -- Valor da leitura para análise
    PRIMARY KEY (sensor_iot_id_sensor, leitura_id_leitura),
    FOREIGN KEY (sensor_iot_id_sensor) REFERENCES sensor_iot(id_sensor),
    FOREIGN KEY (leitura_id_leitura) REFERENCES leitura(id_leitura)
);

-- Tabela Deteccao
CREATE TABLE deteccao (
    id_deteccao NUMBER(9),
    moto_id_moto NUMBER(9),
    camera_id_camera NUMBER(9),
    camera_id_patio NUMBER(9),
    camera_id_filial NUMBER(9),
    data_hora TIMESTAMP(0) NOT NULL,
    coordenadas VARCHAR2(100) NOT NULL,
    PRIMARY KEY (id_deteccao, moto_id_moto),
    FOREIGN KEY (moto_id_moto) REFERENCES moto(id_moto),
    FOREIGN KEY (camera_id_camera, camera_id_patio, camera_id_filial) 
        REFERENCES camera(id_camera, patio_id_patio, patio_id_filial)
);

-- Tabela Manutencao
CREATE TABLE manutencao (
    id_manutencao NUMBER(9),
    moto_id_moto NUMBER(9),
    data DATE NOT NULL,
    descricao CLOB NOT NULL,
    custo NUMBER(10,2) DEFAULT 0, -- Campo adicional para análise
    PRIMARY KEY (id_manutencao, moto_id_moto),
    FOREIGN KEY (moto_id_moto) REFERENCES moto(id_moto)
);

-- Tabela Usuario
CREATE TABLE usuario (
    id_usuario NUMBER(9),
    manutencao_id_manutencao NUMBER(9),
    manutencao_moto_id_moto NUMBER(9),
    nome VARCHAR2(100) NOT NULL,
    cargo VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    PRIMARY KEY (id_usuario, manutencao_id_manutencao, manutencao_moto_id_moto),
    FOREIGN KEY (manutencao_id_manutencao, manutencao_moto_id_moto) 
        REFERENCES manutencao(id_manutencao, moto_id_moto)
);

-- Tabela de Auditoria
CREATE TABLE auditoria (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario VARCHAR2(100),
    tipo_operacao VARCHAR2(10),
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tabela_afetada VARCHAR2(50),
    valores_antigos CLOB,
    valores_novos CLOB
);

-- =============================================================================
-- INSERÇÃO DE DADOS
-- =============================================================================

-- Inserindo dados na tabela filial
INSERT INTO filial (id_filial, nome, endereco) VALUES (1, 'Filial São Paulo', 'Av. Paulista, 1000 - SP');
INSERT INTO filial (id_filial, nome, endereco) VALUES (2, 'Filial Rio de Janeiro', 'Av. Copacabana, 500 - RJ');
INSERT INTO filial (id_filial, nome, endereco) VALUES (3, 'Filial Belo Horizonte', 'Rua da Bahia, 200 - MG');
INSERT INTO filial (id_filial, nome, endereco) VALUES (4, 'Filial Brasília', 'Asa Sul, Quadra 100 - DF');
INSERT INTO filial (id_filial, nome, endereco) VALUES (5, 'Filial Salvador', 'Av. Sete de Setembro, 300 - BA');

-- Inserindo dados na tabela statusmoto
INSERT INTO statusmoto (id_status, descricao) VALUES (1, 'Disponível');
INSERT INTO statusmoto (id_status, descricao) VALUES (2, 'Em Uso');
INSERT INTO statusmoto (id_status, descricao) VALUES (3, 'Manutenção');
INSERT INTO statusmoto (id_status, descricao) VALUES (4, 'Indisponível');
INSERT INTO statusmoto (id_status, descricao) VALUES (5, 'Reservada');

-- Inserindo dados na tabela patio
INSERT INTO patio (id_patio, filial_id_filial, nome, localizacao, largura, comprimento, area_total) 
VALUES (1, 1, 'Pátio Principal SP', 'Entrada Norte', 50.5, 80.2, 4050.10);
INSERT INTO patio (id_patio, filial_id_filial, nome, localizacao, largura, comprimento, area_total) 
VALUES (2, 1, 'Pátio Secundário SP', 'Lateral Oeste', 30.0, 60.0, 1800.00);
INSERT INTO patio (id_patio, filial_id_filial, nome, localizacao, largura, comprimento, area_total) 
VALUES (1, 2, 'Pátio Principal RJ', 'Entrada Principal', 45.5, 70.8, 3221.40);
INSERT INTO patio (id_patio, filial_id_filial, nome, localizacao, largura, comprimento, area_total) 
VALUES (1, 3, 'Pátio BH Centro', 'Area Central', 40.0, 65.0, 2600.00);
INSERT INTO patio (id_patio, filial_id_filial, nome, localizacao, largura, comprimento, area_total) 
VALUES (1, 4, 'Pátio Brasília', 'Setor Norte', 55.2, 75.8, 4184.16);

-- Inserindo dados na tabela camera
INSERT INTO camera (id_camera, patio_id_patio, patio_id_filial, localizacao, modelo) 
VALUES (1, 1, 1, 'Portão Principal', 'Sony IP-2000');
INSERT INTO camera (id_camera, patio_id_patio, patio_id_filial, localizacao, modelo) 
VALUES (2, 1, 1, 'Area Central', 'Canon Security-X1');
INSERT INTO camera (id_camera, patio_id_patio, patio_id_filial, localizacao, modelo) 
VALUES (1, 2, 1, 'Lateral Direita', 'Hikvision DS-200');
INSERT INTO camera (id_camera, patio_id_patio, patio_id_filial, localizacao, modelo) 
VALUES (1, 1, 2, 'Entrada RJ', 'Sony IP-3000');
INSERT INTO camera (id_camera, patio_id_patio, patio_id_filial, localizacao, modelo) 
VALUES (1, 1, 3, 'Centro BH', 'Samsung Security Pro');

-- Inserindo dados na tabela leitura
INSERT INTO leitura (id_leitura, data_hora) VALUES (1, TIMESTAMP '2024-09-01 08:30:00');
INSERT INTO leitura (id_leitura, data_hora) VALUES (2, TIMESTAMP '2024-09-01 14:15:00');
INSERT INTO leitura (id_leitura, data_hora) VALUES (3, TIMESTAMP '2024-09-02 09:45:00');
INSERT INTO leitura (id_leitura, data_hora) VALUES (4, TIMESTAMP '2024-09-02 16:20:00');
INSERT INTO leitura (id_leitura, data_hora) VALUES (5, TIMESTAMP '2024-09-03 11:10:00');

-- Inserindo dados na tabela moto (sem sensor inicialmente)
INSERT INTO moto (id_moto, placa, ano_fabricacao, statusmoto_id_status, patio_id_patio, patio_filial_id_filial) 
VALUES (1, 'ABC-1234', DATE '2022-01-15', 1, 1, 1);
INSERT INTO moto (id_moto, placa, ano_fabricacao, statusmoto_id_status, patio_id_patio, patio_filial_id_filial) 
VALUES (2, 'DEF-5678', DATE '2023-03-20', 2, 1, 1);
INSERT INTO moto (id_moto, placa, ano_fabricacao, statusmoto_id_status, patio_id_patio, patio_filial_id_filial) 
VALUES (3, 'GHI-9012', DATE '2021-11-10', 3, 2, 1);
INSERT INTO moto (id_moto, placa, ano_fabricacao, statusmoto_id_status, patio_id_patio, patio_filial_id_filial) 
VALUES (4, 'JKL-3456', DATE '2023-07-05', 1, 1, 2);
INSERT INTO moto (id_moto, placa, ano_fabricacao, statusmoto_id_status, patio_id_patio, patio_filial_id_filial) 
VALUES (5, 'MNO-7890', DATE '2022-09-12', 4, 1, 3);

-- Inserindo dados na tabela sensor_iot
INSERT INTO sensor_iot (id_sensor, tipo, fabricante, moto_id_moto) 
VALUES (1, 'GPS', 'Garmin Tech', 1);
INSERT INTO sensor_iot (id_sensor, tipo, fabricante, moto_id_moto) 
VALUES (2, 'Acelerômetro', 'Bosch IoT', 2);
INSERT INTO sensor_iot (id_sensor, tipo, fabricante, moto_id_moto) 
VALUES (3, 'Temperatura', 'Siemens Sensors', 3);
INSERT INTO sensor_iot (id_sensor, tipo, fabricante, moto_id_moto) 
VALUES (4, 'Velocidade', 'Intel IoT Solutions', 4);
INSERT INTO sensor_iot (id_sensor, tipo, fabricante, moto_id_moto) 
VALUES (5, 'Bateria', 'Samsung IoT', 5);

-- Atualizando motos com sensores
UPDATE moto SET sensor_iot_id_sensor = 1 WHERE id_moto = 1;
UPDATE moto SET sensor_iot_id_sensor = 2 WHERE id_moto = 2;
UPDATE moto SET sensor_iot_id_sensor = 3 WHERE id_moto = 3;
UPDATE moto SET sensor_iot_id_sensor = 4 WHERE id_moto = 4;
UPDATE moto SET sensor_iot_id_sensor = 5 WHERE id_moto = 5;

-- Inserindo dados na tabela sensor_leitura
INSERT INTO sensor_leitura (sensor_iot_id_sensor, leitura_id_leitura, valor) VALUES (1, 1, 25.5);
INSERT INTO sensor_leitura (sensor_iot_id_sensor, leitura_id_leitura, valor) VALUES (2, 2, 1200.0);
INSERT INTO sensor_leitura (sensor_iot_id_sensor, leitura_id_leitura, valor) VALUES (3, 3, 68.2);
INSERT INTO sensor_leitura (sensor_iot_id_sensor, leitura_id_leitura, valor) VALUES (4, 4, 45.8);
INSERT INTO sensor_leitura (sensor_iot_id_sensor, leitura_id_leitura, valor) VALUES (5, 5, 87.3);

-- Inserindo dados na tabela deteccao
INSERT INTO deteccao (id_deteccao, moto_id_moto, camera_id_camera, camera_id_patio, camera_id_filial, data_hora, coordenadas) 
VALUES (1, 1, 1, 1, 1, TIMESTAMP '2024-09-01 09:00:00', '(-23.561684, -46.625290)');
INSERT INTO deteccao (id_deteccao, moto_id_moto, camera_id_camera, camera_id_patio, camera_id_filial, data_hora, coordenadas) 
VALUES (2, 2, 2, 1, 1, TIMESTAMP '2024-09-01 14:30:00', '(-23.561234, -46.625567)');
INSERT INTO deteccao (id_deteccao, moto_id_moto, camera_id_camera, camera_id_patio, camera_id_filial, data_hora, coordenadas) 
VALUES (3, 3, 1, 2, 1, TIMESTAMP '2024-09-02 10:15:00', '(-23.562001, -46.624890)');
INSERT INTO deteccao (id_deteccao, moto_id_moto, camera_id_camera, camera_id_patio, camera_id_filial, data_hora, coordenadas) 
VALUES (4, 4, 1, 1, 2, TIMESTAMP '2024-09-02 16:45:00', '(-22.906847, -43.172896)');
INSERT INTO deteccao (id_deteccao, moto_id_moto, camera_id_camera, camera_id_patio, camera_id_filial, data_hora, coordenadas) 
VALUES (5, 5, 1, 1, 3, TIMESTAMP '2024-09-03 11:30:00', '(-19.912998, -43.940933)');

-- Inserindo dados na tabela manutencao
INSERT INTO manutencao (id_manutencao, moto_id_moto, data, descricao, custo) 
VALUES (1, 1, DATE '2024-08-15', 'Troca de óleo e filtros', 150.00);
INSERT INTO manutencao (id_manutencao, moto_id_moto, data, descricao, custo) 
VALUES (2, 2, DATE '2024-08-20', 'Revisão geral do sistema elétrico', 300.50);
INSERT INTO manutencao (id_manutencao, moto_id_moto, data, descricao, custo) 
VALUES (3, 3, DATE '2024-09-01', 'Reparo do sistema de freios', 225.75);
INSERT INTO manutencao (id_manutencao, moto_id_moto, data, descricao, custo) 
VALUES (4, 4, DATE '2024-09-05', 'Substituição de pneus', 180.00);
INSERT INTO manutencao (id_manutencao, moto_id_moto, data, descricao, custo) 
VALUES (5, 5, DATE '2024-09-10', 'Manutenção preventiva completa', 420.25);

-- Inserindo dados na tabela usuario
INSERT INTO usuario (id_usuario, manutencao_id_manutencao, manutencao_moto_id_moto, nome, cargo, email) 
VALUES (1, 1, 1, 'Carlos Silva', 'Mecânico', 'carlos.silva@mottu.com');
INSERT INTO usuario (id_usuario, manutencao_id_manutencao, manutencao_moto_id_moto, nome, cargo, email) 
VALUES (2, 2, 2, 'Ana Santos', 'Técnica Elétrica', 'ana.santos@mottu.com');
INSERT INTO usuario (id_usuario, manutencao_id_manutencao, manutencao_moto_id_moto, nome, cargo, email) 
VALUES (3, 3, 3, 'Pedro Oliveira', 'Especialista em Freios', 'pedro.oliveira@mottu.com');
INSERT INTO usuario (id_usuario, manutencao_id_manutencao, manutencao_moto_id_moto, nome, cargo, email) 
VALUES (4, 4, 4, 'Maria Costa', 'Técnica Geral', 'maria.costa@mottu.com');
INSERT INTO usuario (id_usuario, manutencao_id_manutencao, manutencao_moto_id_moto, nome, cargo, email) 
VALUES (5, 5, 5, 'João Pereira', 'Supervisor', 'joao.pereira@mottu.com');

COMMIT;

-- =============================================================================
-- FUNÇÃO 1: CONVERSÃO MANUAL PARA JSON
-- =============================================================================

CREATE OR REPLACE FUNCTION converter_para_json(
    p_tabela VARCHAR2,
    p_condicao VARCHAR2 DEFAULT NULL
) RETURN CLOB
IS
    v_json CLOB := '';
    v_first BOOLEAN := TRUE;
    v_cursor SYS_REFCURSOR;
    v_sql VARCHAR2(4000);
    
    -- Variáveis para diferentes tipos de consulta
    v_id_moto NUMBER;
    v_placa VARCHAR2(10);
    v_nome_filial VARCHAR2(100);
    v_nome_patio VARCHAR2(100);
    v_status_desc VARCHAR2(50);
    v_ano_fabricacao DATE;
    
    -- Exceções personalizadas
    TABELA_INEXISTENTE EXCEPTION;
    CONSULTA_INVALIDA EXCEPTION;
    DADOS_INSUFICIENTES EXCEPTION;
    
BEGIN
    -- Validação da tabela
    IF p_tabela IS NULL OR LENGTH(TRIM(p_tabela)) = 0 THEN
        RAISE TABELA_INEXISTENTE;
    END IF;
    
    -- Início do JSON
    v_json := '[';
    
    -- Query específica para moto com JOIN
    IF UPPER(p_tabela) = 'MOTO_COMPLETA' THEN
        v_sql := 'SELECT m.id_moto, m.placa, f.nome as nome_filial, p.nome as nome_patio, s.descricao as status_desc, m.ano_fabricacao
                  FROM moto m
                  JOIN patio p ON (m.patio_id_patio = p.id_patio AND m.patio_filial_id_filial = p.filial_id_filial)
                  JOIN filial f ON p.filial_id_filial = f.id_filial
                  JOIN statusmoto s ON m.statusmoto_id_status = s.id_status';
        
        IF p_condicao IS NOT NULL THEN
            v_sql := v_sql || ' WHERE ' || p_condicao;
        END IF;
        
        OPEN v_cursor FOR v_sql;
        
        LOOP
            FETCH v_cursor INTO v_id_moto, v_placa, v_nome_filial, v_nome_patio, v_status_desc, v_ano_fabricacao;
            EXIT WHEN v_cursor%NOTFOUND;
            
            IF NOT v_first THEN
                v_json := v_json || ',';
            END IF;
            
            -- Montagem manual do JSON
            v_json := v_json || '{' ||
                     '"id_moto":' || v_id_moto || ',' ||
                     '"placa":"' || v_placa || '",' ||
                     '"filial":"' || v_nome_filial || '",' ||
                     '"patio":"' || v_nome_patio || '",' ||
                     '"status":"' || v_status_desc || '",' ||
                     '"ano":"' || TO_CHAR(v_ano_fabricacao, 'YYYY') || '"' ||
                     '}';
            
            v_first := FALSE;
        END LOOP;
        
        CLOSE v_cursor;
        
    ELSE
        RAISE CONSULTA_INVALIDA;
    END IF;
    
    -- Verifica se encontrou dados
    IF v_first THEN
        RAISE DADOS_INSUFICIENTES;
    END IF;
    
    -- Finalização do JSON
    v_json := v_json || ']';
    
    RETURN v_json;

EXCEPTION
    WHEN TABELA_INEXISTENTE THEN
        RETURN '{"erro": "Tabela não especificada ou inválida"}';
    WHEN CONSULTA_INVALIDA THEN
        RETURN '{"erro": "Tipo de consulta não suportado"}';
    WHEN DADOS_INSUFICIENTES THEN
        RETURN '{"erro": "Nenhum dado encontrado para os critérios especificados"}';
    WHEN OTHERS THEN
        RETURN '{"erro": "Erro interno: ' || SQLERRM || '"}';
END converter_para_json;
/

-- =============================================================================
-- FUNÇÃO 2: VALIDAÇÃO DE PLACA DE MOTO
-- =============================================================================

CREATE OR REPLACE FUNCTION validar_placa_moto(
    p_placa VARCHAR2
) RETURN VARCHAR2
IS
    v_resultado VARCHAR2(100);
    v_count NUMBER;
    v_formato_valido NUMBER := 0;
    
    -- Exceções personalizadas
    PLACA_NULA EXCEPTION;
    PLACA_DUPLICADA EXCEPTION;
    FORMATO_INVALIDO EXCEPTION;
    
BEGIN
    -- Validação: placa não pode ser nula
    IF p_placa IS NULL OR LENGTH(TRIM(p_placa)) = 0 THEN
        RAISE PLACA_NULA;
    END IF;
    
    -- Validação do formato da placa (ABC-1234)
    SELECT CASE 
        WHEN REGEXP_LIKE(UPPER(TRIM(p_placa)), '^[A-Z]{3}-[0-9]{4}$') THEN 1
        ELSE 0
    END INTO v_formato_valido FROM DUAL;
    
    IF v_formato_valido = 0 THEN
        RAISE FORMATO_INVALIDO;
    END IF;
    
    -- Verificação de duplicação
    SELECT COUNT(*) INTO v_count 
    FROM moto 
    WHERE UPPER(placa) = UPPER(TRIM(p_placa));
    
    IF v_count > 0 THEN
        RAISE PLACA_DUPLICADA;
    END IF;
    
    -- Se passou em todas as validações
    v_resultado := 'VÁLIDA: Placa ' || UPPER(TRIM(p_placa)) || ' aprovada para cadastro';
    
    RETURN v_resultado;

EXCEPTION
    WHEN PLACA_NULA THEN
        RETURN 'INVÁLIDA: Placa não pode ser nula ou vazia';
    WHEN FORMATO_INVALIDO THEN
        RETURN 'INVÁLIDA: Formato deve ser ABC-1234 (3 letras, hífen, 4 números)';
    WHEN PLACA_DUPLICADA THEN
        RETURN 'INVÁLIDA: Placa já cadastrada no sistema';
    WHEN OTHERS THEN
        RETURN 'ERRO: ' || SQLERRM;
END validar_placa_moto;
/

-- =============================================================================
-- PROCEDIMENTO 1: EXIBIÇÃO DE DADOS COM JOIN EM FORMATO JSON
-- =============================================================================

CREATE OR REPLACE PROCEDURE exibir_motos_json(
    p_filtro_status VARCHAR2 DEFAULT NULL
)
IS
    v_json_result CLOB;
    v_count NUMBER := 0;
    
    -- Exceções personalizadas
    STATUS_INEXISTENTE EXCEPTION;
    ERRO_CONVERSAO EXCEPTION;
    NENHUM_DADO EXCEPTION;
    
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== RELATÓRIO DE MOTOS EM FORMATO JSON ===');
    DBMS_OUTPUT.PUT_LINE('Data/Hora: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
    DBMS_OUTPUT.PUT_LINE('');
    
    -- Validação do filtro de status se fornecido
    IF p_filtro_status IS NOT NULL THEN
        SELECT COUNT(*) INTO v_count 
        FROM statusmoto 
        WHERE UPPER(descricao) = UPPER(p_filtro_status);
        
        IF v_count = 0 THEN
            RAISE STATUS_INEXISTENTE;
        END IF;
    END IF;
    
    -- Chamada da função de conversão JSON
    IF p_filtro_status IS NOT NULL THEN
        v_json_result := converter_para_json('MOTO_COMPLETA', 
            'UPPER(s.descricao) = UPPER(''' || p_filtro_status || ''')');
    ELSE
        v_json_result := converter_para_json('MOTO_COMPLETA');
    END IF;
    
    -- Verificação se houve erro na conversão
    IF v_json_result LIKE '%"erro"%' THEN
        RAISE ERRO_CONVERSAO;
    END IF;
    
    -- Verificação se há dados
    IF v_json_result = '[]' THEN
        RAISE NENHUM_DADO;
    END IF;
    
    -- Exibição do resultado JSON
    DBMS_OUTPUT.PUT_LINE('JSON Result:');
    DBMS_OUTPUT.PUT_LINE(v_json_result);
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('=== FIM DO RELATÓRIO ===');

EXCEPTION
    WHEN STATUS_INEXISTENTE THEN
        DBMS_OUTPUT.PUT_LINE('ERRO: Status "' || p_filtro_status || '" não encontrado no sistema');
    WHEN ERRO_CONVERSAO THEN
        DBMS_OUTPUT.PUT_LINE('ERRO: Falha na conversão para JSON: ' || v_json_result);
    WHEN NENHUM_DADO THEN
        DBMS_OUTPUT.PUT_LINE('AVISO: Nenhum dado encontrado para os critérios especificados');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERRO INESPERADO: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Código do erro: ' || SQLCODE);
END exibir_motos_json;
/

-- =============================================================================
-- PROCEDIMENTO 2: RELATÓRIO DE CUSTOS DE MANUTENÇÃO COM TOTALIZAÇÕES MANUAIS
-- =============================================================================

CREATE OR REPLACE PROCEDURE relatorio_custos_manutencao
IS
    -- Variáveis para armazenar dados
    TYPE t_manutencao IS RECORD (
        nome_filial VARCHAR2(100),
        cargo_usuario VARCHAR2(50),
        custo NUMBER(10,2)
    );
    
    TYPE t_tab_manutencao IS TABLE OF t_manutencao INDEX BY PLS_INTEGER;
    v_dados t_tab_manutencao;
    
    -- Variáveis de controle
    v_index NUMBER := 1;
    v_filial_anterior VARCHAR2(100) := '';
    v_subtotal_filial NUMBER(10,2) := 0;
    v_total_geral NUMBER(10,2) := 0;
    v_count_registros NUMBER := 0;
    
    -- Cursor para dados ordenados
    CURSOR c_dados IS
        SELECT f.nome as nome_filial,
               u.cargo,
               m.custo
        FROM manutencao m
        JOIN moto mo ON m.moto_id_moto = mo.id_moto
        JOIN patio p ON (mo.patio_id_patio = p.id_patio AND mo.patio_filial_id_filial = p.filial_id_filial)
        JOIN filial f ON p.filial_id_filial = f.id_filial
        JOIN usuario u ON (m.id_manutencao = u.manutencao_id_manutencao AND m.moto_id_moto = u.manutencao_moto_id_moto)
        ORDER BY f.nome, u.cargo;
    
    -- Exceções personalizadas  
    DADOS_INSUFICIENTES EXCEPTION;
    ERRO_CALCULO EXCEPTION;
    CURSOR_ERRO EXCEPTION;
    
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== RELATÓRIO DE CUSTOS DE MANUTENÇÃO ===');
    DBMS_OUTPUT.PUT_LINE('Data: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'));
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE(RPAD('FILIAL', 25) || RPAD('CARGO', 20) || RPAD('CUSTO', 15));
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 25, '-') || RPAD('-', 20, '-') || RPAD('-', 15, '-'));
    
    -- Carregamento dos dados no array
    FOR rec IN c_dados LOOP
        v_dados(v_index).nome_filial := rec.nome_filial;
        v_dados(v_index).cargo_usuario := rec.cargo;
        v_dados(v_index).custo := rec.custo;
        v_index := v_index + 1;
        v_count_registros := v_count_registros + 1;
    END LOOP;
    
    -- Verificação se há dados suficientes
    IF v_count_registros < 5 THEN
        RAISE DADOS_INSUFICIENTES;
    END IF;
    
    -- Processamento manual dos totais
    FOR i IN 1..v_dados.COUNT LOOP
        -- Quebra por filial (subtotal)
        IF v_filial_anterior != v_dados(i).nome_filial AND v_filial_anterior != '' THEN
            -- Exibe subtotal da filial anterior
            DBMS_OUTPUT.PUT_LINE(RPAD(' ', 25) || RPAD('SUBTOTAL', 20) || RPAD(TO_CHAR(v_subtotal_filial, '999,999.99'), 15));
            DBMS_OUTPUT.PUT_LINE('');
            v_subtotal_filial := 0;
        END IF;
        
        -- Exibe linha de detalhe
        DBMS_OUTPUT.PUT_LINE(RPAD(v_dados(i).nome_filial, 25) || 
                           RPAD(v_dados(i).cargo_usuario, 20) || 
                           RPAD(TO_CHAR(v_dados(i).custo, '999,999.99'), 15));
        
        -- Acumula totais
        v_subtotal_filial := v_subtotal_filial + v_dados(i).custo;
        v_total_geral := v_total_geral + v_dados(i).custo;
        
        -- Atualiza filial anterior
        v_filial_anterior := v_dados(i).nome_filial;
    END LOOP;
    
    -- Subtotal da última filial
    IF v_subtotal_filial > 0 THEN
        DBMS_OUTPUT.PUT_LINE(RPAD(' ', 25) || RPAD('SUBTOTAL', 20) || RPAD(TO_CHAR(v_subtotal_filial, '999,999.99'), 15));
        DBMS_OUTPUT.PUT_LINE('');
    END IF;
    
    -- Total geral
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 60, '-'));
    DBMS_OUTPUT.PUT_LINE(RPAD(' ', 25) || RPAD('TOTAL GERAL', 20) || RPAD(TO_CHAR(v_total_geral, '999,999.99'), 15));
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('Registros processados: ' || v_count_registros);
    DBMS_OUTPUT.PUT_LINE('=== FIM DO RELATÓRIO ===');

EXCEPTION
    WHEN DADOS_INSUFICIENTES THEN
        DBMS_OUTPUT.PUT_LINE('ERRO: Dados insuficientes. Mínimo de 5 registros requeridos.');
        DBMS_OUTPUT.PUT_LINE('Registros encontrados: ' || v_count_registros);
    WHEN ERRO_CALCULO THEN
        DBMS_OUTPUT.PUT_LINE('ERRO: Falha nos cálculos de totalização');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERRO INESPERADO: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Posição: ' || v_index);
END relatorio_custos_manutencao;
/

-- =============================================================================
-- TRIGGER DE AUDITORIA
-- =============================================================================

CREATE OR REPLACE TRIGGER tr_auditoria_moto
    AFTER INSERT OR UPDATE OR DELETE ON moto
    FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_valores_antigos CLOB;
    v_valores_novos CLOB;
    v_usuario VARCHAR2(100);
BEGIN
    -- Determina o tipo de operação
    IF INSERTING THEN
        v_operacao := 'INSERT';
    ELSIF UPDATING THEN  
        v_operacao := 'UPDATE';
    ELSIF DELETING THEN
        v_operacao := 'DELETE';
    END IF;
    
    -- Captura o usuário atual
    SELECT USER INTO v_usuario FROM DUAL;
    
    -- Monta valores antigos (OLD)
    IF UPDATING OR DELETING THEN
        v_valores_antigos := 'id_moto:' || :OLD.id_moto || 
                           '|placa:' || :OLD.placa ||
                           '|ano_fabricacao:' || TO_CHAR(:OLD.ano_fabricacao, 'DD/MM/YYYY') ||
                           '|sensor_iot_id:' || :OLD.sensor_iot_id_sensor ||
                           '|status_id:' || :OLD.statusmoto_id_status ||
                           '|patio_id:' || :OLD.patio_id_patio ||
                           '|filial_id:' || :OLD.patio_filial_id_filial;
    END IF;
    
    -- Monta valores novos (NEW)
    IF INSERTING OR UPDATING THEN
        v_valores_novos := 'id_moto:' || :NEW.id_moto || 
                         '|placa:' || :NEW.placa ||
                         '|ano_fabricacao:' || TO_CHAR(:NEW.ano_fabricacao, 'DD/MM/YYYY') ||
                         '|sensor_iot_id:' || :NEW.sensor_iot_id_sensor ||
                         '|status_id:' || :NEW.statusmoto_id_status ||
                         '|patio_id:' || :NEW.patio_id_patio ||
                         '|filial_id:' || :NEW.patio_filial_id_filial;
    END IF;
    
    -- Insere registro na tabela de auditoria
    INSERT INTO auditoria (
        nome_usuario,
        tipo_operacao, 
        tabela_afetada,
        valores_antigos,
        valores_novos
    ) VALUES (
        v_usuario,
        v_operacao,
        'MOTO',
        v_valores_antigos,
        v_valores_novos
    );
    
EXCEPTION
    WHEN OTHERS THEN
        -- Em caso de erro na auditoria, registra erro mas não impede a operação principal
        INSERT INTO auditoria (
            nome_usuario,
            tipo_operacao,
            tabela_afetada, 
            valores_antigos,
            valores_novos
        ) VALUES (
            USER,
            'ERROR',
            'MOTO',
            'ERRO_TRIGGER: ' || SQLERRM,
            NULL
        );
END tr_auditoria_moto;
/

-- =============================================================================
-- SCRIPTS DE TESTE E DEMONSTRAÇÃO
-- =============================================================================

-- Teste da Função 1 (Conversão JSON)
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TESTE FUNÇÃO CONVERSÃO JSON ===');
    DBMS_OUTPUT.PUT_LINE(converter_para_json('MOTO_COMPLETA'));
    DBMS_OUTPUT.PUT_LINE('');
    
    -- Teste com filtro
    DBMS_OUTPUT.PUT_LINE('=== TESTE COM FILTRO STATUS ===');
    DBMS_OUTPUT.PUT_LINE(converter_para_json('MOTO_COMPLETA', 's.id_status = 1'));
    DBMS_OUTPUT.PUT_LINE('');
END;
/

PROMPT TESTE 1: Parâmetro tabela NULL ou vazio
PROMPT -----------------------------------------

BEGIN
    DBMS_OUTPUT.PUT_LINE('🧪 TESTE 1A: Parâmetro p_tabela = NULL');
    DBMS_OUTPUT.PUT_LINE('Chamada: converter_para_json(NULL)');
    DBMS_OUTPUT.PUT_LINE('Resultado esperado: Exceção TABELA_INEXISTENTE');
    DBMS_OUTPUT.PUT_LINE('');
    
    DECLARE
        v_resultado CLOB;
    BEGIN
        v_resultado := converter_para_json(NULL);
        DBMS_OUTPUT.PUT_LINE('Resultado obtido: ' || v_resultado);
    END;
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('✅ Status: SUCESSO - Exceção capturada corretamente');
    DBMS_OUTPUT.PUT_LINE('');
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('❌ ERRO INESPERADO: ' || SQLERRM);
END;
/

-- Teste da Função 2 (Validação de Placa)
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TESTE FUNÇÃO VALIDAÇÃO PLACA ===');
    DBMS_OUTPUT.PUT_LINE('Teste 1: ' || validar_placa_moto('XYZ-9999'));
    DBMS_OUTPUT.PUT_LINE('Teste 2: ' || validar_placa_moto('ABC123')); -- Formato inválido
    DBMS_OUTPUT.PUT_LINE('Teste 3: ' || validar_placa_moto('ABC-1234')); -- Duplicada
    DBMS_OUTPUT.PUT_LINE('Teste 4: ' || validar_placa_moto('')); -- Vazia
    DBMS_OUTPUT.PUT_LINE('');
END;
/

-- Teste do Procedimento 1
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TESTE PROCEDIMENTO EXIBIR MOTOS JSON ===');
    exibir_motos_json();
    DBMS_OUTPUT.PUT_LINE('');
    
    -- Teste com filtro
    DBMS_OUTPUT.PUT_LINE('=== TESTE COM FILTRO DISPONÍVEL ===');
    exibir_motos_json('Disponível');
    DBMS_OUTPUT.PUT_LINE('');
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Teste 1.1A: Status completamente inexistente');
    DBMS_OUTPUT.PUT_LINE('Chamada: exibir_motos_json(''StatusInexistente'')');
    DBMS_OUTPUT.PUT_LINE('Exceção esperada: STATUS_INEXISTENTE');
    DBMS_OUTPUT.PUT_LINE('');
    
    exibir_motos_json('StatusInexistente');
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('❌ ERRO INESPERADO: ' || SQLERRM);
END;
/



-- Teste do Procedimento 2  
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== TESTE PROCEDIMENTO RELATÓRIO CUSTOS ===');
    relatorio_custos_manutencao();
    DBMS_OUTPUT.PUT_LINE('');
END;
/

CREATE TABLE temp_backup_manutencao AS SELECT * FROM manutencao;
CREATE TABLE temp_backup_usuario AS SELECT * FROM usuario;

-- Limpar dados para forçar exceção
DELETE FROM usuario;
DELETE FROM manutencao;
COMMIT;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Teste 2.1A: Sem dados suficientes (< 5 registros)');
    DBMS_OUTPUT.PUT_LINE('Chamada: relatorio_custos_manutencao()');
    DBMS_OUTPUT.PUT_LINE('Exceção esperada: DADOS_INSUFICIENTES');
    DBMS_OUTPUT.PUT_LINE('');
    
    relatorio_custos_manutencao();
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('❌ ERRO INESPERADO: ' || SQLERRM);
END;
/

-- Teste do Trigger (INSERT)
INSERT INTO moto (id_moto, placa, ano_fabricacao, statusmoto_id_status, patio_id_patio, patio_filial_id_filial)
VALUES (6, 'TEST-0001', DATE '2024-01-01', 1, 1, 1);

-- Teste do Trigger (UPDATE)  
UPDATE moto SET statusmoto_id_status = 3 WHERE id_moto = 6;

-- Teste do Trigger (DELETE)
DELETE FROM moto WHERE id_moto = 6;

-- Consulta dos registros de auditoria
SELECT * FROM auditoria ORDER BY data_hora DESC;

COMMIT;

-- =============================================================================
-- FIM DO SCRIPT
-- =============================================================================