INSERT INTO USUARIO (USERNAME, PASSWORD, PERFIL) VALUES ('admin', '{noop}admin123', 'ROLE_ADMIN');
INSERT INTO USUARIO (USERNAME, PASSWORD, PERFIL) VALUES ('user', '{noop}user123', 'ROLE_FUNCIONARIO');

INSERT INTO PATIO (NOME, ENDERECO) VALUES ('Patio Norte', 'Rua XPTO, 123');
INSERT INTO PATIO (NOME, ENDERECO) VALUES ('Patio Sul', 'Avenida ABC, 456');

INSERT INTO MOTO (PLACA, MODELO, PATIO_ID) VALUES ('ABC1D23', 'Mottu Sport 110i', 1);
INSERT INTO MOTO (PLACA, MODELO, PATIO_ID) VALUES ('DEF4G56', 'Mottu Delivery 2023', 2);

COMMIT;
